In [5]:
!python main.py

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 8869274 bytes (8662 KiB)

Extracting archive: D:\python_projects\ztm-at-night\files\RA190409.7z
--
Path = D:\python_projects\ztm-at-night\files\RA190409.7z
Type = 7z
Physical Size = 8869274
Headers Size = 126
Method = LZMA:24
Solid = -
Blocks = 1

Everything is Ok

Size:       244594601
Compressed: 8869274
RA190409.7z
Local directory already contains latest file: RA190409.7z
RA190409.7z
Parsing section ZA - stops
118151,Okrągła 51,,
133151,Nauczycielska 51,,
153152,Podgórna 52,,
427251,Kostowiec 51,,
429552,Żabieniec 52,,
wrong stops size 5
Parsing section LL - routes and times
Parsing line:    Linia:   1  - LINIA TRAMWAJOWA
Parsing line:    Linia:   2  - LINIA TRAMWAJOWA
Parsing line:    Linia:   3  - LINIA TRAMWAJOWA
Parsing line:    Linia:   4  - LINIA TRAMWAJOWA
Parsing line:    Linia:   6  - LINIA TRAMWAJOWA
Parsing line:    Linia:   7  - LINIA TRAMWAJOWA
Parsing line:    Linia:   9  - LINIA TRAMWAJOWA
Parsing line:    Linia:  10  - LINIA TRAMWAJOWA
Parsing line:    Linia:  11  - LINIA TRAMWAJOWA
Parsing line:    Linia:  13  - LINIA TRAMWAJOWA
Parsing line:    Linia:  14  - LINIA TRAMWAJOWA
Parsing line:    Linia:  15  - LINIA TRAMWAJOWA
Parsing line:    Linia:  17  - LINIA TRAMWAJOWA
Parsing line:    Linia:  18  - LINIA TRAMWAJOWA
Parsing line:    Linia:  20  - LINIA TRAMWAJOWA
Parsing line:    Linia:  22  - LINIA TRAMWAJOWA
Parsing line:    Linia:  23  - LINIA TRAMWAJOWA
Parsing line:    Linia:  24  - LINIA TRAMWAJOWA
Parsing line:    Linia:  25  - LINIA TRAMWAJOWA
Parsing line:    Linia:  26  - LINIA TRAMWAJOWA
Parsing line:    Linia:  27  - LINIA TRAMWAJOWA
Parsing line:    Linia:  28  - LINIA TRAMWAJOWA
Parsing line:    Linia:  31  - LINIA TRAMWAJOWA
Parsing line:    Linia:  33  - LINIA TRAMWAJOWA
Parsing line:    Linia:  35  - LINIA TRAMWAJOWA
Parsing line:    Linia:  41  - LINIA TRAMWAJOWA OKRESOWA
Parsing line:    Linia: 102  - LINIA ZWYKŁA
Parsing line:    Linia: 103  - LINIA ZWYKŁA
Parsing line:    Linia: 104  - LINIA ZWYKŁA
Parsing line:    Linia: 105  - LINIA ZWYKŁA
Parsing line:    Linia: 107  - LINIA ZWYKŁA
Parsing line:    Linia: 108  - LINIA ZWYKŁA
Parsing line:    Linia: 109  - LINIA ZWYKŁA
Parsing line:    Linia: 110  - LINIA ZWYKŁA
Parsing line:    Linia: 111  - LINIA ZWYKŁA
Parsing line:    Linia: 112  - LINIA ZWYKŁA
Parsing line:    Linia: 114  - LINIA ZWYKŁA
Parsing line:    Linia: 115  - LINIA ZWYKŁA
Parsing line:    Linia: 116  - LINIA ZWYKŁA
Parsing line:    Linia: 117  - LINIA ZWYKŁA
Parsing line:    Linia: 118  - LINIA ZWYKŁA
Parsing line:    Linia: 119  - LINIA ZWYKŁA
Parsing line:    Linia: 120  - LINIA ZWYKŁA
Parsing line:    Linia: 121  - LINIA ZWYKŁA
Parsing line:    Linia: 122  - LINIA ZWYKŁA
Parsing line:    Linia: 123  - LINIA ZWYKŁA
Parsing line:    Linia: 124  - LINIA ZWYKŁA
Parsing line:    Linia: 125  - LINIA ZWYKŁA
Parsing line:    Linia: 126  - LINIA ZWYKŁA
Parsing line:    Linia: 127  - LINIA ZWYKŁA
Parsing line:    Linia: 128  - LINIA ZWYKŁA
Parsing line:    Linia: 129  - LINIA ZWYKŁA
Parsing line:    Linia: 130  - LINIA ZWYKŁA
Parsing line:    Linia: 131  - LINIA ZWYKŁA
Parsing line:    Linia: 132  - LINIA ZWYKŁA
Parsing line:    Linia: 133  - LINIA ZWYKŁA
Parsing line:    Linia: 134  - LINIA ZWYKŁA
Parsing line:    Linia: 135  - LINIA ZWYKŁA
Parsing line:    Linia: 136  - LINIA ZWYKŁA
Parsing line:    Linia: 138  - LINIA ZWYKŁA
Parsing line:    Linia: 139  - LINIA ZWYKŁA
Parsing line:    Linia: 140  - LINIA ZWYKŁA
Parsing line:    Linia: 141  - LINIA ZWYKŁA
Parsing line:    Linia: 142  - LINIA ZWYKŁA
Parsing line:    Linia: 143  - LINIA ZWYKŁA
Parsing line:    Linia: 145  - LINIA ZWYKŁA
Parsing line:    Linia: 146  - LINIA ZWYKŁA
Parsing line:    Linia: 147  - LINIA ZWYKŁA
Parsing line:    Linia: 148  - LINIA ZWYKŁA
Parsing line:    Linia: 149  - LINIA ZWYKŁA
Parsing line:    Linia: 150  - LINIA ZWYKŁA
Parsing line:    Linia: 151  - LINIA ZWYKŁA
Parsing line:    Linia: 152  - LINIA ZWYKŁA
Parsing line:    Linia: 153  - LINIA ZWYKŁA
Parsing line:    Linia: 154  - LINIA ZWYKŁA
Parsing line:    Linia: 155  - LINIA ZWYKŁA
Parsing line:    Linia: 156  - LINIA ZWYKŁA
Parsing line:    Linia: 157  - LINIA ZWYKŁA
Parsing line:    Linia: 158  - LINIA ZWYKŁA
Parsing line:    Linia: 159  - LINIA ZWYKŁA
Parsing line:    Linia: 160  - LINIA ZWYKŁA
Parsing line:    Linia: 161  - LINIA ZWYKŁA
Parsing line:    Linia: 162  - LINIA ZWYKŁA
Parsing line:    Linia: 163  - LINIA ZWYKŁA
Parsing line:    Linia: 164  - LINIA ZWYKŁA
Parsing line:    Linia: 165  - LINIA ZWYKŁA
Parsing line:    Linia: 166  - LINIA ZWYKŁA
Parsing line:    Linia: 167  - LINIA ZWYKŁA
Parsing line:    Linia: 168  - LINIA ZWYKŁA
Parsing line:    Linia: 169  - LINIA ZWYKŁA
Parsing line:    Linia: 170  - LINIA ZWYKŁA
Parsing line:    Linia: 171  - LINIA ZWYKŁA
Parsing line:    Linia: 172  - LINIA ZWYKŁA
Parsing line:    Linia: 173  - LINIA ZWYKŁA
Parsing line:    Linia: 174  - LINIA ZWYKŁA
Parsing line:    Linia: 175  - LINIA ZWYKŁA
Parsing line:    Linia: 176  - LINIA ZWYKŁA
Parsing line:    Linia: 177  - LINIA ZWYKŁA
Parsing line:    Linia: 178  - LINIA ZWYKŁA
Parsing line:    Linia: 179  - LINIA ZWYKŁA
Parsing line:    Linia: 180  - LINIA ZWYKŁA
Parsing line:    Linia: 181  - LINIA ZWYKŁA
Parsing line:    Linia: 182  - LINIA ZWYKŁA
Parsing line:    Linia: 183  - LINIA ZWYKŁA
Parsing line:    Linia: 184  - LINIA ZWYKŁA
Parsing line:    Linia: 185  - LINIA ZWYKŁA
Parsing line:    Linia: 186  - LINIA ZWYKŁA
Parsing line:    Linia: 187  - LINIA ZWYKŁA
Parsing line:    Linia: 188  - LINIA ZWYKŁA
Parsing line:    Linia: 189  - LINIA ZWYKŁA
Parsing line:    Linia: 190  - LINIA ZWYKŁA
Parsing line:    Linia: 191  - LINIA ZWYKŁA
Parsing line:    Linia: 192  - LINIA ZWYKŁA
Parsing line:    Linia: 193  - LINIA ZWYKŁA
Parsing line:    Linia: 194  - LINIA ZWYKŁA
Parsing line:    Linia: 195  - LINIA ZWYKŁA
Parsing line:    Linia: 196  - LINIA ZWYKŁA
Parsing line:    Linia: 197  - LINIA ZWYKŁA
Parsing line:    Linia: 198  - LINIA ZWYKŁA
Parsing line:    Linia: 199  - LINIA ZWYKŁA
Parsing line:    Linia: 200  - LINIA ZWYKŁA
Parsing line:    Linia: 201  - LINIA ZWYKŁA
Parsing line:    Linia: 202  - LINIA ZWYKŁA
Parsing line:    Linia: 203  - LINIA ZWYKŁA
Parsing line:    Linia: 204  - LINIA ZWYKŁA
Parsing line:    Linia: 205  - LINIA ZWYKŁA
Parsing line:    Linia: 206  - LINIA ZWYKŁA
Parsing line:    Linia: 207  - LINIA ZWYKŁA
Parsing line:    Linia: 208  - LINIA ZWYKŁA
Parsing line:    Linia: 209  - LINIA ZWYKŁA
Parsing line:    Linia: 210  - LINIA ZWYKŁA
Parsing line:    Linia: 211  - LINIA ZWYKŁA
Parsing line:    Linia: 212  - LINIA ZWYKŁA
Parsing line:    Linia: 213  - LINIA ZWYKŁA
Parsing line:    Linia: 214  - LINIA ZWYKŁA
Parsing line:    Linia: 217  - LINIA ZWYKŁA
Parsing line:    Linia: 218  - LINIA ZWYKŁA
Parsing line:    Linia: 219  - LINIA ZWYKŁA
Parsing line:    Linia: 220  - LINIA ZWYKŁA
Parsing line:    Linia: 221  - LINIA ZWYKŁA
Parsing line:    Linia: 222  - LINIA ZWYKŁA
Parsing line:    Linia: 225  - LINIA ZWYKŁA
Parsing line:    Linia: 227  - LINIA ZWYKŁA
Parsing line:    Linia: 228  - LINIA ZWYKŁA
Parsing line:    Linia: 239  - LINIA ZWYKŁA
Parsing line:    Linia: 240  - LINIA ZWYKŁA
Parsing line:    Linia: 245  - LINIA ZWYKŁA
Parsing line:    Linia: 249  - LINIA ZWYKŁA
Parsing line:    Linia: 250  - LINIA ZWYKŁA
Parsing line:    Linia: 251  - LINIA ZWYKŁA
Parsing line:    Linia: 255  - LINIA ZWYKŁA
Parsing line:    Linia: 256  - LINIA ZWYKŁA
Parsing line:    Linia: 262  - LINIA ZWYKŁA
Parsing line:    Linia: 264  - LINIA ZWYKŁA
Parsing line:    Linia: 303  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 304  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 305  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 308  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 311  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 317  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 318  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 320  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 323  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 326  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 327  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 328  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 331  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 332  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 334  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 338  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 339  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 340  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 345  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 365  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 379  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 397  - LINIA ZWYKŁA OKRESOWA
Parsing line:    Linia: 401  - LINIA PRZYSPIESZONA OKRESOWA
Parsing line:    Linia: 402  - LINIA PRZYSPIESZONA OKRESOWA
Parsing line:    Linia: 409  - LINIA PRZYSPIESZONA OKRESOWA
Parsing line:    Linia: 411  - LINIA PRZYSPIESZONA OKRESOWA
Parsing line:    Linia: 412  - LINIA PRZYSPIESZONA OKRESOWA
Parsing line:    Linia: 414  - LINIA PRZYSPIESZONA OKRESOWA
Parsing line:    Linia: 500  - LINIA PRZYSPIESZONA
Parsing line:    Linia: 501  - LINIA PRZYSPIESZONA
Parsing line:    Linia: 502  - LINIA PRZYSPIESZONA
Parsing line:    Linia: 503  - LINIA PRZYSPIESZONA
Parsing line:    Linia: 504  - LINIA PRZYSPIESZONA
Parsing line:    Linia: 507  - LINIA PRZYSPIESZONA
Parsing line:    Linia: 509  - LINIA PRZYSPIESZONA
Parsing line:    Linia: 511  - LINIA PRZYSPIESZONA
Parsing line:    Linia: 512  - LINIA PRZYSPIESZONA
Parsing line:    Linia: 514  - LINIA PRZYSPIESZONA
Parsing line:    Linia: 516  - LINIA PRZYSPIESZONA
Parsing line:    Linia: 517  - LINIA PRZYSPIESZONA
Parsing line:    Linia: 518  - LINIA PRZYSPIESZONA
Parsing line:    Linia: 519  - LINIA PRZYSPIESZONA
Parsing line:    Linia: 520  - LINIA PRZYSPIESZONA
Parsing line:    Linia: 521  - LINIA PRZYSPIESZONA
Parsing line:    Linia: 522  - LINIA PRZYSPIESZONA
Parsing line:    Linia: 523  - LINIA PRZYSPIESZONA
Parsing line:    Linia: 525  - LINIA PRZYSPIESZONA
Parsing line:    Linia: 527  - LINIA PRZYSPIESZONA
Parsing line:    Linia: 702  - LINIA STREFOWA
Parsing line:    Linia: 703  - LINIA STREFOWA
Parsing line:    Linia: 704  - LINIA STREFOWA
Parsing line:    Linia: 705  - LINIA STREFOWA
Parsing line:    Linia: 706  - LINIA STREFOWA
Parsing line:    Linia: 707  - LINIA STREFOWA
Parsing line:    Linia: 709  - LINIA STREFOWA
Parsing line:    Linia: 710  - LINIA STREFOWA
Parsing line:    Linia: 711  - LINIA STREFOWA
Parsing line:    Linia: 712  - LINIA STREFOWA
Parsing line:    Linia: 713  - LINIA STREFOWA
Parsing line:    Linia: 714  - LINIA STREFOWA
Parsing line:    Linia: 715  - LINIA STREFOWA
Parsing line:    Linia: 716  - LINIA STREFOWA
Parsing line:    Linia: 717  - LINIA STREFOWA
Parsing line:    Linia: 719  - LINIA STREFOWA
Parsing line:    Linia: 720  - LINIA STREFOWA
Parsing line:    Linia: 721  - LINIA STREFOWA
Parsing line:    Linia: 722  - LINIA STREFOWA
Parsing line:    Linia: 723  - LINIA STREFOWA
Parsing line:    Linia: 724  - LINIA STREFOWA
Parsing line:    Linia: 727  - LINIA STREFOWA
Parsing line:    Linia: 728  - LINIA STREFOWA
Parsing line:    Linia: 729  - LINIA STREFOWA
Parsing line:    Linia: 730  - LINIA STREFOWA
Parsing line:    Linia: 731  - LINIA STREFOWA
Parsing line:    Linia: 733  - LINIA STREFOWA
Parsing line:    Linia: 734  - LINIA STREFOWA
Parsing line:    Linia: 735  - LINIA STREFOWA
Parsing line:    Linia: 736  - LINIA STREFOWA
Parsing line:    Linia: 737  - LINIA STREFOWA
Parsing line:    Linia: 738  - LINIA STREFOWA
Parsing line:    Linia: 739  - LINIA STREFOWA
Parsing line:    Linia: 741  - LINIA STREFOWA
Parsing line:    Linia: 742  - LINIA STREFOWA
Parsing line:    Linia: 743  - LINIA STREFOWA
Parsing line:    Linia: 750  - LINIA STREFOWA
Parsing line:    Linia: 800  - LINIA STREFOWA OKRESOWA
Parsing line:    Linia: 900  - LINIA SPECJALNA
Parsing line:    Linia: E-1  - LINIA EKSPRESOWA
Parsing line:    Linia: E-2  - LINIA EKSPRESOWA
Parsing line:    Linia: E-7  - LINIA EKSPRESOWA
Parsing line:    Linia: E-9  - LINIA EKSPRESOWA
Parsing line:    Linia: L-1  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L-2  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L-3  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L-4  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L-5  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L-6  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L-7  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L-8  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L-9  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L10  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L11  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L12  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L13  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L14  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L15  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L16  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L17  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L18  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L19  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L20  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L21  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L22  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L23  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L24  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L25  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L26  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L27  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L28  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L29  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L30  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L31  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L32  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L33  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L34  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L35  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L36  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L37  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L38  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L39  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L40  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L41  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L42  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L43  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L44  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L45  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L46  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L47  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: L48  - LINIA STREFOWA UZUPEŁNIAJĄCA
Parsing line:    Linia: N01  - LINIA NOCNA
Parsing line:    Linia: N02  - LINIA NOCNA
Parsing line:    Linia: N03  - LINIA NOCNA
Parsing line:    Linia: N11  - LINIA NOCNA
Parsing line:    Linia: N12  - LINIA NOCNA
Parsing line:    Linia: N13  - LINIA NOCNA
Parsing line:    Linia: N14  - LINIA NOCNA
Parsing line:    Linia: N16  - LINIA NOCNA
Parsing line:    Linia: N21  - LINIA NOCNA
Parsing line:    Linia: N22  - LINIA NOCNA
Parsing line:    Linia: N24  - LINIA NOCNA
Parsing line:    Linia: N25  - LINIA NOCNA
Parsing line:    Linia: N31  - LINIA NOCNA
Parsing line:    Linia: N32  - LINIA NOCNA
Parsing line:    Linia: N33  - LINIA NOCNA
Parsing line:    Linia: N34  - LINIA NOCNA
Parsing line:    Linia: N35  - LINIA NOCNA
Parsing line:    Linia: N36  - LINIA NOCNA
Parsing line:    Linia: N37  - LINIA NOCNA
Parsing line:    Linia: N38  - LINIA NOCNA
Parsing line:    Linia: N41  - LINIA NOCNA
Parsing line:    Linia: N42  - LINIA NOCNA
Parsing line:    Linia: N43  - LINIA NOCNA
Parsing line:    Linia: N44  - LINIA NOCNA
Parsing line:    Linia: N45  - LINIA NOCNA
Parsing line:    Linia: N46  - LINIA NOCNA
Parsing line:    Linia: N50  - LINIA NOCNA
Parsing line:    Linia: N52  - LINIA NOCNA
Parsing line:    Linia: N56  - LINIA NOCNA
Parsing line:    Linia: N58  - LINIA NOCNA
Parsing line:    Linia: N61  - LINIA NOCNA
Parsing line:    Linia: N62  - LINIA NOCNA
Parsing line:    Linia: N63  - LINIA NOCNA
Parsing line:    Linia: N64  - LINIA NOCNA
Parsing line:    Linia: N66  - LINIA NOCNA
Parsing line:    Linia: N71  - LINIA NOCNA
Parsing line:    Linia: N72  - LINIA NOCNA
Parsing line:    Linia: N81  - LINIA NOCNA
Parsing line:    Linia: N83  - LINIA NOCNA
Parsing line:    Linia: N85  - LINIA NOCNA
Parsing line:    Linia: N88  - LINIA NOCNA
Parsing line:    Linia: N91  - LINIA NOCNA
Parsing line:    Linia: N95  - LINIA NOCNA
Parsing line:    Linia:  R1  - LINIA KOLEI MAZOWIECKICH STREFOWA
Parsing line:    Linia:  R2  - LINIA KOLEI MAZOWIECKICH STREFOWA
Parsing line:    Linia:  R3  - LINIA KOLEI MAZOWIECKICH STREFOWA
Parsing line:    Linia:  R6  - LINIA KOLEI MAZOWIECKICH STREFOWA
Parsing line:    Linia:  R7  - LINIA KOLEI MAZOWIECKICH STREFOWA
Parsing line:    Linia:  R8  - LINIA KOLEI MAZOWIECKICH STREFOWA
Parsing line:    Linia:  R9  - LINIA KOLEI MAZOWIECKICH STREFOWA
Parsing line:    Linia:  RL  - LINIA KOLEI MAZOWIECKICH STREFOWA
Parsing line:    Linia:  S1  - LINIA KOLEI MIEJSKIEJ
Parsing line:    Linia:  S2  - LINIA KOLEI MIEJSKIEJ
Parsing line:    Linia:  S3  - LINIA KOLEI MIEJSKIEJ
Parsing line:    Linia:  S9  - LINIA KOLEI MIEJSKIEJ
Parsing line:    Linia: WKD  - LINIA WARSZAWSKIEJ KOLEI DOJAZDOWEJ

In [4]:
import pandas as pd

In [102]:
stops = pd.read_csv('results/stops.txt', encoding = 'cp1250')
stop_times = pd.read_csv('results/stop_times.txt')
trips = pd.read_csv('results/trips.txt')

In [103]:
stops.head()

   stop_id    stop_name   stop_lon   stop_lat
0   100101  Kijowska 01  52.248456  21.044827
1   100102  Kijowska 02  52.249076  21.044441
2   100103  Kijowska 03  52.248998  21.043983
3   100104  Kijowska 04  52.249905  21.041726
4   100105  Kijowska 05  52.250320  21.043861

In [104]:
stop_times.head()

   trip_id arrival_time departure_time  stop_id  stop_sequence
0        1      4:04:00        4:04:00   324004              1
1        1      4:06:00        4:06:00   323904              2
2        1      4:07:00        4:07:00   323804              3
3        1      4:08:00        4:08:00   323704              4
4        1      4:09:00        4:09:00   328604              5

In [105]:
trips.head()

  route_id service_id  trip_id
0        1         DP        1
1        1         DS        2
2        1         SB        3
3        1         DP        4
4        1         DP        5

In [106]:
print(trips.service_id.unique())
# ['NP' 'NS' 'NO']

trips = trips[trips.service_id.isin(['NP', 'NS', 'NO'])]
print(len(trips))
trips.head()

['DP' 'DS' 'SB' 'NP' 'NS' 'NO']
278

     route_id service_id  trip_id
2772      N01         NP     2773
2773      N01         NS     2774
2774      N01         NP     2775
2775      N01         NS     2776
2776      N01         NP     2777

In [107]:
stop_times = stop_times[stop_times.trip_id.isin(trips.trip_id)]

stop_times['arrival_time_s'] = (stop_times['arrival_time'].str.extract("(\d{2}):\d{2}:\d{2}").astype(int)*60*60 + 
    stop_times['arrival_time'].str.extract("\d{2}:(\d{2}):\d{2}").astype(int)*60 + 
    stop_times['arrival_time'].str.extract("\d{2}:\d{2}:(\d{2})").astype(int))/60

stop_times['departure_time_s'] = (stop_times['departure_time'].str.extract("(\d{2}):\d{2}:\d{2}").astype(int)*60*60 + 
    stop_times['departure_time'].str.extract("\d{2}:(\d{2}):\d{2}").astype(int)*60 + 
    stop_times['departure_time'].str.extract("\d{2}:\d{2}:(\d{2})").astype(int))/60

stop_times.head()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,arrival_time_s,departure_time_s
1925043,2773,23:58:00,23:58:00,409002,1,1438.0,1438.0
1925044,2773,23:59:00,23:59:00,409102,2,1439.0,1439.0
1925045,2773,24:00:00,24:00:00,409202,3,1440.0,1440.0
1925046,2773,24:01:00,24:01:00,421402,4,1441.0,1441.0
1925047,2773,24:02:00,24:02:00,421302,5,1442.0,1442.0

In [108]:
all(stop_times.arrival_time_s == stop_times.departure_time_s)
# True

stop_times.drop(["departure_time","departure_time_s"], axis = 1, inplace = True)

In [123]:
print(min(stop_times.arrival_time_s),max(stop_times.arrival_time_s))

1305.0 1826.0

In [116]:
stops_times_count = stop_times.groupby(["stop_id","arrival_time_s"]).size()
stops_times_count

stop_id  arrival_time_s
100101   1380.0            1
         1407.0            1
         1408.0            1
         1417.0            2
         1439.0            1
         1443.0            1
         1446.0            2
         1468.0            2
         1479.0            2
         1499.0            1
         1503.0            1
         1509.0            2
         1528.0            1
         1529.0            1
         1535.0            2
         1559.0            1
         1563.0            1
         1565.0            2
         1588.0            1
         1589.0            1
         1595.0            2
         1619.0            1
         1623.0            1
         1625.0            2
         1648.0            1
         1653.0            1
         1658.0            2
         1678.0            1
         1683.0            1
         1688.0            2
                          ..
709901   1440.0            1
         1500.0            1
         1559.0            1
         1619.0            1
         1679.0            1
         1739.0            1
709902   1403.0            1
         1433.0            1
         1463.0            1
         1493.0            1
         1523.0            1
         1553.0            1
         1583.0            1
         1613.0            1
         1643.0            1
         1673.0            1
         1703.0            1
         1733.0            1
709910   1374.0            1
         1434.0            1
         1468.0            1
         1494.0            1
         1524.0            1
         1554.0            1
         1584.0            1
         1614.0            1
         1644.0            1
         1674.0            1
         1704.0            1
         1734.0            1
Length: 25000, dtype: int64

In [120]:
stops_times_count.sort_values()

stop_id  arrival_time_s
100101   1380.0            1
501601   1523.0            1
         1643.0            1
501602   1498.0            1
         1618.0            1
502052   1414.0            1
         1415.0            1
         1444.0            1
         1445.0            1
         1473.0            1
         1474.0            1
         1503.0            1
         1504.0            1
501502   1761.0            1
502052   1532.0            1
         1562.0            1
         1563.0            1
         1592.0            1
         1593.0            1
         1622.0            1
         1623.0            1
         1652.0            1
         1653.0            1
         1682.0            1
         1683.0            1
         1712.0            1
         1713.0            1
         1533.0            1
501502   1701.0            1
         1641.0            1
                          ..
701305   1488.0            6
700227   1665.0            6
         1575.0            6
701305   1458.0            6
700227   1605.0            6
701305   1428.0            6
         1398.0            6
         1698.0            6
700225   1665.0            6
701305   1728.0            6
700227   1485.0            6
700225   1725.0            6
700227   1635.0            6
329802   1424.0            6
703301   1699.0            6
         1669.0            6
327902   1426.0            6
703301   1639.0            6
         1609.0            6
700227   1395.0            6
703301   1579.0            6
         1549.0            6
700227   1425.0            6
703301   1519.0            6
         1489.0            6
         1459.0            6
700227   1455.0            6
703301   1429.0            6
         1399.0            6
700225   1425.0            6
Length: 25000, dtype: int64